# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0805c2fc8cd9e7aa5f1d3e767e7765d2"
application_url = "https://expires-pmid-consequences-inquire.trycloudflare.com"
embedded = true
name = "Before & After Image"
handle = "before-after-image"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://expires-pmid-consequences-inquire.trycloudflare.com/auth/callback",
  "https://expires-pmid-consequences-inquire.trycloudflare.com/auth/shopify/callback",
  "https://expires-pmid-consequences-inquire.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "abc123425.myshopify.com"
automatically_update_urls_on_dev = true
